<Project>
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.props.user" Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.props.user')" />

  <PropertyGroup>
    <ModName>DaCard</ModName>
    <ModAuthor>Guro</ModAuthor>
    <Version>2.1.0</Version>

    <SptPackageVersion>4.1.5</SptPackageVersion>

    <SptGameDir Condition="'$(SptGameDir)' == ''"></SptGameDir>

    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <ReleaseStagingDir>$(RepoRoot)artifacts\staging\</ReleaseStagingDir>

    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
